### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by jonathantneal**

### CODE REVIEW

**Comment by hacknug** [comment]
@jonathantneal have some tests passing on my computer. Will take another look at it tomorrow if that's not an issue 🙏

**Comment by jonathantneal** [comment]
@hacknug, that is not an issue. I can revisit this plugin tomorrow if you do not have a chance to update the PR. Thank you!

**Comment by hacknug** [comment]
0% confident on what I did but all tests are passing so… 🤷‍♂ https://github.com/hacknug/postcss-custom-utils/commit/5808073417df6a11fb4bc3193d31646f2bf7669f

Can't push directly to this repo so let me know what should I do once you've had a chance to review the changes.

**Comment by jonathantneal** [comment]
@hacknug, wow, it looks like you nailed it! So, child nodes of a function no longer include the parenthesis, which is great, and which is why you ended up removing `.slice(1, -1)`.

I’m not sure why you’re unable to push to this repo. I will look into that immediately.

**Comment by jonathantneal** [comment]
@hacknug, I’ve adjusted permissions so that you and @oliverturner should have complete write control. I’m sorry I did not catch this earlier. Please let me know if it is working now.

**Comment by hacknug** [comment]
Can't push yet:

```bash
postcss-custom-utils git:(next) git remote add upstream https://github.com/csstools/postcss-custom-utils.git
postcss-custom-utils git:(next) git push upstream next
remote: Permission to csstools/postcss-custom-utils.git denied to hacknug.
fatal: unable to access 'https://github.com/csstools/postcss-custom-utils.git/': The requested URL returned error: 403
```

**Comment by jonathantneal** [comment]
@hacknug, I made another adjustment. Would you mind trying again?

**Comment by hacknug** [comment]
@jonathantneal no luck (probably something I'm doing wrong or my computer's fault). Maybe I can open a new PR from my fork? Your commit would still be there so it would be pretty much the same, no?

**Comment by jonathantneal** [comment]
That is fine with me, @hacknug. Thanks!

**Comment by jonathantneal** [comment]
I’m still reviewing this merge of mine, with your work on top of it.

**Comment by hacknug** [comment]
Sorry!

**Comment by jonathantneal** [comment]
@hacknug, I’ve merged in your tests, only commenting out the broken ones.

**Pull request merged**
